### ISSUE TITLE
Joint effort for WIT syntax highlighter 

### ISSUE THREAD

**Issue by eduardomourar** [badeend/vscode-wit#1]
We have the following WIT syntax highlighter within the BCA organization: https://github.com/bytecodealliance/vscode-wit

That definition is driving the highlight within GitHub. Could we work together on it?

**Comment by badeend** [comment]
Thanks for reaching out. I posted something similar a few days ago https://github.com/bytecodealliance/vscode-wit/issues/21 :) 

The auxiliary features of this extension are pretty standalone and should be easy to port over (markdown highlighting, auto-continuing doc-comments, basic autocomplete).

As for the WIT syntax definition itself, we'll have to discuss that further in detail. But in principle; Yes, we could work together on it.

**Comment by badeend** [comment]
Closing in favor of https://github.com/bytecodealliance/vscode-wit/issues/21
